<Type Name="TargetInvocationException" FullName="System.Reflection.TargetInvocationException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="e3f83cc27a236d4e545014be5ac189c0b5531b4b" />
    <Meta Name="ms.sourcegitcommit" Value="c0c07dbd19cd7017243f9ac36915755f79bc8da6" />
    <Meta Name="ms.translationtype" Value="MT" />
    <Meta Name="ms.contentlocale" Value="pl-PL" />
    <Meta Name="ms.lasthandoff" Value="11/27/2018" />
    <Meta Name="ms.locfileid" Value="52385033" />
  </Metadata>
  <TypeSignature Language="C#" Value="public sealed class TargetInvocationException : ApplicationException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit TargetInvocationException extends System.ApplicationException" />
  <TypeSignature Language="DocId" Value="T:System.Reflection.TargetInvocationException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class TargetInvocationException&#xA;Inherits ApplicationException" />
  <TypeSignature Language="C++ CLI" Value="public ref class TargetInvocationException sealed : ApplicationException" />
  <TypeSignature Language="F#" Value="type TargetInvocationException = class&#xA;    inherit ApplicationException" />
  <AssemblyInfo>
    <AssemblyName>System.Reflection</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.10.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>1.0.5000.0</AssemblyVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
    <BaseTypeName FrameworkAlternate="netframework-4.5">System.ApplicationException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-1.1;netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0">
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="9be4c-101">Wyjątek, który jest generowany przez metody wywoływane za pośrednictwem odbicia.</span>
      <span class="sxs-lookup">
        <span data-stu-id="9be4c-101">The exception that is thrown by methods invoked through reflection.</span>
      </span>
      <span data-ttu-id="9be4c-102">Klasa ta nie może być dziedziczona.</span>
      <span class="sxs-lookup">
        <span data-stu-id="9be4c-102">This class cannot be inherited.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="9be4c-103">Aby uzyskać więcej informacji, zobacz <xref:System.Reflection.MethodBase.Invoke%2A>.</span><span class="sxs-lookup"><span data-stu-id="9be4c-103">For more information, see <xref:System.Reflection.MethodBase.Invoke%2A>.</span></span>  
  
 <span data-ttu-id="9be4c-104">`TargetInvocationException` używa COR_E_TARGETINVOCATION HRESULT, która ma wartość 0x80131604.</span><span class="sxs-lookup"><span data-stu-id="9be4c-104">`TargetInvocationException` uses the HRESULT COR_E_TARGETINVOCATION which has the value 0x80131604.</span></span>  
  
 <span data-ttu-id="9be4c-105">Podczas tworzenia `TargetInvocationException` jest przekazywany odwołania do wyjątku zgłoszonego przez metody wywoływane za pośrednictwem odbicia.</span><span class="sxs-lookup"><span data-stu-id="9be4c-105">When created, the `TargetInvocationException` is passed a reference to the exception thrown by the method invoked through reflection.</span></span> <span data-ttu-id="9be4c-106"><xref:System.Exception.InnerException%2A> Właściwość przechowuje bazowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="9be4c-106">The <xref:System.Exception.InnerException%2A> property holds the underlying exception.</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="P:System.Exception.InnerException" />
    <altmember cref="T:System.Exception" />
    <related type="Article" href="~/docs/standard/exceptions/index.md">
      <span data-ttu-id="9be4c-107">Obsługa i zgłaszanie wyjątków na platformie .NET</span>
      <span class="sxs-lookup">
        <span data-stu-id="9be4c-107">Handling and throwing exceptions in .NET</span>
      </span>
    </related>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Reflection</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="9be4c-108">Inicjuje nowe wystąpienie klasy <see cref="T:System.Reflection.TargetInvocationException" /> klasy.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-108">Initializes a new instance of the <see cref="T:System.Reflection.TargetInvocationException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public TargetInvocationException (Exception inner);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception inner) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.TargetInvocationException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (inner As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; TargetInvocationException(Exception ^ inner);" />
      <MemberSignature Language="F#" Value="new System.Reflection.TargetInvocationException : Exception -&gt; System.Reflection.TargetInvocationException" Usage="new System.Reflection.TargetInvocationException inner" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Reflection</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="inner" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="inner">
          <span data-ttu-id="9be4c-109">Wyjątek, który jest przyczyną bieżącego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-109">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="9be4c-110">Jeśli <paramref name="inner" /> parametr nie jest <see langword="null" />, bieżący wyjątek jest zgłaszany w <see langword="catch" /> blok, który obsługuje wyjątek wewnętrzny.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-110">If the <paramref name="inner" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="9be4c-111">Inicjuje nowe wystąpienie klasy <see cref="T:System.Reflection.TargetInvocationException" /> klasy z odwołaniem do wewnętrznego wyjątku, który jest przyczyną tego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-111">Initializes a new instance of the <see cref="T:System.Reflection.TargetInvocationException" /> class with a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="9be4c-112">Wyjątek generowany jako bezpośredni wynik poprzedniego wyjątku powinien zawierać odwołanie do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A> właściwości.</span><span class="sxs-lookup"><span data-stu-id="9be4c-112">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="9be4c-113"><xref:System.Exception.InnerException%2A> Właściwość zwraca taką samą wartość, która jest przekazywana do konstruktora, lub `null` Jeśli <xref:System.Exception.InnerException%2A> nie dostarcza wartości wewnętrznego wyjątku do konstruktora.</span><span class="sxs-lookup"><span data-stu-id="9be4c-113">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="9be4c-114">W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:System.Reflection.TargetInvocationException>.</span><span class="sxs-lookup"><span data-stu-id="9be4c-114">The following table shows the initial property values for an instance of <xref:System.Reflection.TargetInvocationException>.</span></span>  
  
|<span data-ttu-id="9be4c-115">Właściwość</span><span class="sxs-lookup"><span data-stu-id="9be4c-115">Property</span></span>|<span data-ttu-id="9be4c-116">Wartość</span><span class="sxs-lookup"><span data-stu-id="9be4c-116">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="9be4c-117">Odwołanie do wewnętrznego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="9be4c-117">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="9be4c-118">Ciąg komunikatu o błędzie.</span><span class="sxs-lookup"><span data-stu-id="9be4c-118">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <related type="Article" href="~/docs/standard/exceptions/index.md">
          <span data-ttu-id="9be4c-119">Obsługa i zgłaszanie wyjątków na platformie .NET</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-119">Handling and throwing exceptions in .NET</span>
          </span>
        </related>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public TargetInvocationException (string message, Exception inner);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception inner) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.TargetInvocationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, inner As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; TargetInvocationException(System::String ^ message, Exception ^ inner);" />
      <MemberSignature Language="F#" Value="new System.Reflection.TargetInvocationException : string * Exception -&gt; System.Reflection.TargetInvocationException" Usage="new System.Reflection.TargetInvocationException (message, inner)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Reflection</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="inner" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="9be4c-120">Komunikat o błędzie wyjaśniający przyczynę wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-120">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="inner">
          <span data-ttu-id="9be4c-121">Wyjątek, który jest przyczyną bieżącego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-121">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="9be4c-122">Jeśli <paramref name="inner" /> parametr nie jest <see langword="null" />, bieżący wyjątek jest zgłaszany w <see langword="catch" /> blok, który obsługuje wyjątek wewnętrzny.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-122">If the <paramref name="inner" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="9be4c-123">Inicjuje nowe wystąpienie klasy <see cref="T:System.Reflection.TargetInvocationException" /> klasy przy użyciu określonego komunikatu o błędzie i odwołania do wewnętrznego wyjątku, który jest przyczyną tego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-123">Initializes a new instance of the <see cref="T:System.Reflection.TargetInvocationException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="9be4c-124">Wyjątek generowany jako bezpośredni wynik poprzedniego wyjątku powinien zawierać odwołanie do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A> właściwości.</span><span class="sxs-lookup"><span data-stu-id="9be4c-124">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="9be4c-125"><xref:System.Exception.InnerException%2A> Właściwość zwraca taką samą wartość, która jest przekazywana do konstruktora, lub `null` Jeśli <xref:System.Exception.InnerException%2A> nie dostarcza wartości wewnętrznego wyjątku do konstruktora.</span><span class="sxs-lookup"><span data-stu-id="9be4c-125">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="9be4c-126">W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:System.Reflection.TargetInvocationException>.</span><span class="sxs-lookup"><span data-stu-id="9be4c-126">The following table shows the initial property values for an instance of <xref:System.Reflection.TargetInvocationException>.</span></span>  
  
|<span data-ttu-id="9be4c-127">Właściwość</span><span class="sxs-lookup"><span data-stu-id="9be4c-127">Property</span></span>|<span data-ttu-id="9be4c-128">Wartość</span><span class="sxs-lookup"><span data-stu-id="9be4c-128">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="9be4c-129">Odwołanie do wewnętrznego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="9be4c-129">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="9be4c-130">Ciąg komunikatu o błędzie.</span><span class="sxs-lookup"><span data-stu-id="9be4c-130">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <related type="Article" href="~/docs/standard/exceptions/index.md">
          <span data-ttu-id="9be4c-131">Obsługa i zgłaszanie wyjątków na platformie .NET</span>
          <span class="sxs-lookup">
            <span data-stu-id="9be4c-131">Handling and throwing exceptions in .NET</span>
          </span>
        </related>
      </Docs>
    </Member>
  </Members>
</Type>